apiVersion: apps/v1
kind: Deployment
metadata:
  name: merly-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merly-ui
  template:
    metadata:
      labels:
        app: merly-ui
    spec:
      containers:
        - name: merly-ui
          image: merlyai/merly-mentor-ui:v0.1.0
          ports:
            - containerPort: 3000
          env:
            - name: MERLY_AI_BRIDGE_URL
              value: "http://merly-bridge:8080"
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: merly-ui
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: merly-ui
